Tsk 28 add redux storage
Ma1ve/BattleCity pull request #14
Opened 2023-08-25 10:04 UTC by Ma1ve

Добавил в проект Redux-Toolkit. 
- Фейковые данные, которые были на странице Profile будут храниться в UserSlice. 

- Немного изменил роутер, добавил проверку,  теперь не все страницы могут отображаться, если в store не будет данных user (в дальнейшем, как я думаю, мы будет получать их автоматически с сервера и записывать в stor ). 

- Перезаписать данные user, можно заполнив поля в форме регистрации 

- Изменил **opacity** заднего фона на 0.95 вместо 1 

![qwe](https://github.com/Ma1ve/BattleCity/assets/93385505/73b68e90-227c-4d2d-aef1-e909aad81cb6)

**_Важно:_**
Если данных user в store не будет, к некоторым страницам не будет доступа, **будет показывать Page 404**.

2023-08-25 21:28 UTC, vasilek-liza approved these changes
Отличная работа! оставила пару комментов)

2023-08-25 21:28 UTC, vasilek-liza commented on packages/client/src/app/models/IUser.ts
> +  avatar: null
avatar не будет всегда null, тут наверное правильно было б avatar: null | string

2023-08-25 21:28 UTC, vasilek-liza commented on packages/client/src/app/store/reducers/UserSlice.ts
> +  userInfo: [
а почему у нас userInfo это массив с объектом, а не просто объект?

2023-08-26 06:41 UTC, stepanpr approved these changes
Отличная работа!

2023-08-26 06:41 UTC, stepanpr commented on lerna-debug.log
lerna-debug.log Файл с логами не нужно добавлять в коммит )

2023-08-26 06:41 UTC, stepanpr commented on yarn.lock
также не нужно добавлять в коммит )

2023-08-26 07:51 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/index.tsx
> +  const [user] = useAppSelector(state => state.user.userInfo)
Рекомендация: предлагаю воспользоваться селекторами из toolkit-а
Так код будет оптимизированее
https://redux-toolkit.js.org/api/createSelector

2023-08-26 07:52 UTC, IvanPeleshok commented on packages/client/src/app/store/reducers/UserSlice.ts
> +  userInfo: [
Аналогичный вопрос

2023-08-26 07:54 UTC, IvanPeleshok commented on packages/client/src/app/hooks/reducer.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
Предлагаю ознакомиться с видосиком по типизации
Тогда не придётся кастить типы для диспатчера и т.д
https://www.youtube.com/watch?v=NKg5K1b7ljg

2023-08-26 07:55 UTC, IvanPeleshok commented on packages/client/src/app/models/IUser.ts
> +  avatar: null
Аналогично, необходимо поправить

2023-08-26 07:56 UTC, IvanPeleshok commented on packages/client/src/pages/Login/index.tsx
> +    navigate('/game')
Можно подумать о том, чтобы вынести все роуты в объект / enum, а в дальнейшем переиспользовать

2023-08-26 07:56 UTC, IvanPeleshok commented on packages/client/src/pages/Login/index.tsx
> +    navigate('/game')
И profile ниже

2023-08-26 07:57 UTC, IvanPeleshok requested changes
Проделана огромная работа, но есть небольшие замечания

Нужны доработки

2023-08-28 17:22 UTC, Ma1ve commented on packages/client/src/app/store/reducers/UserSlice.ts
> +  userInfo: [
Я просто думал, что с бэкенда, будет удобнее держать информацию в массиве, чтобы потом проверять пустой ли он или нет. Сейчас понял, раз уж там будет храниться один объект с информацией о user, то думаю массив не нужен.

2023-08-30 16:07 UTC, IvanPeleshok commented
@Ma1ve, привет
Переведи работу на ревью в практикуме
Проверю текущий PR

2023-08-30 19:14 UTC, IvanPeleshok approved these changes
Замечательная работа, апрув :)

2023-08-30 22:27 UTC, merged