Добавлены страницы:
Ma1ve/BattleCity pull request #15
Opened 2023-08-25 18:56 UTC by archibald7812

1. Страница окончания игры
2. Страница загрузки игры

### Какую задачу решаем
Верстка страниц

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-25 20:57 UTC, IvanPeleshok requested changes
Необходим хотя бы один апрув от тимейта

2023-08-25 21:41 UTC, Ma1ve approved these changes
Хорошая работа!

2023-08-25 21:41 UTC, Ma1ve commented on packages/client/src/pages/GameToStart/index.tsx
> +        <div className={styles.loaderIcon}></div>
Если данный Loader будет использоваться во всем проекте, можно создать отдельный компонент, который будет появляться при отправке данных на сервер и тд.

2023-08-25 21:41 UTC, Ma1ve commented on packages/client/src/pages/EndGame/index.tsx
> +      </div>
В компонентах EndGame и GameToStart есть схожие стили, чтобы избежать дублирования, можно создать отдельный компонент на примере GameComponent  (если, конечно, EndGame и GameToStart не будут изменены в дальнейшем) : 
```
const GameComponent = ({ title, children }) => (
  <div className={commonStyles.wrapper}>
    <div className={commonStyles.text}>
      <H1>{title}</H1>
    </div>
    {children}
  </div>
);
```

2023-08-25 21:48 UTC, vasilek-liza requested changes

2023-08-25 21:48 UTC, vasilek-liza commented on packages/client/src/app/RootLayout.tsx
> +            className={({ isActive }) =>
тут хорошо было бы использовать classnames
https://github.com/JedWatson/classnames

2023-08-25 21:48 UTC, vasilek-liza commented on packages/client/src/shared/images/Tank_1.png
а почему ты берешь  png? мне кажется svg было бы здесь уместнее с точки зрения оптимизации)

2023-08-25 21:48 UTC, vasilek-liza commented on packages/client/src/pages/Main/index.tsx
> +//import styles from './gametostart.module.css'
если это в данный момент не используется, лучше удалить и не нести закомменченные строки в пр)

2023-08-25 21:48 UTC, vasilek-liza commented on packages/client/src/pages/EndGame/endgame.module.css
> +.endGameText > div {
лучше использовать классы

2023-08-25 21:48 UTC, vasilek-liza commented on packages/client/package.json
> +}
отсутствует пустая последняя строка в файле

2023-08-25 21:48 UTC, vasilek-liza commented on packages/client/src/pages/Main/index.tsx
> +//import styles from './gametostart.module.css'
то же самое на 5 строке

2023-08-26 06:50 UTC, stepanpr approved these changes
Отличная работа!

2023-08-26 06:50 UTC, stepanpr commented on packages/client/src/pages/EndGame/index.tsx
> +      </div>
Да, так как функция схожа у компонента, то в идеале можно переделать потом чтобы был один компонент с двумя состояниями -  "начало игры" и "конец игры".

2023-08-26 06:50 UTC, stepanpr commented on packages/client/src/pages/GameToStart/index.tsx
> +        <div className={styles.loaderIcon}></div>
Да, как вариант

2023-08-26 07:45 UTC, vasilek-liza approved these changes

2023-08-26 08:54 UTC, archibald7812 commented on packages/client/src/pages/EndGame/endgame.module.css
> +.endGameText > div {
Это тег <H1>, я не стал его менять, но он не подразумевает пробрасывание внешних стилей в него. Если автор этого компонента не против, то можно добавить такую возможность.

2023-08-26 08:56 UTC, archibald7812 commented on packages/client/src/shared/images/Tank_1.png
Просто нашел картинки, обрезал и сохранил в png, можно и конвертировать в svg, так должно быть лучше, спасибо!

2023-08-27 22:16 UTC, IvanPeleshok commented on packages/client/src/app/RootLayout.tsx
> +            className={({ isActive }) =>
Предлагаю ознакомиться https://snyk.io/advisor/npm-package/classnames/example

2023-08-27 22:18 UTC, IvanPeleshok commented on packages/client/src/pages/GameToStart/gametostart.module.css
> +.gameToStartText > div {
Ссылаться относительно дива не очень безопасно
Хорошим подходом будет пользоваться всегда классами, там практически всегда будет уверенность, что именно на этот элемент мы хотим повесить стили

2023-08-27 22:20 UTC, IvanPeleshok commented on packages/client/src/pages/GameToStart/index.tsx
> +import H1 from '../../shared/ui/H1'
Какое практическое применение H1?
Симантически это див, никакой особой пользы он не несёт
Название не очень понятное, почему бы тогда не воспользоваться <h1 /> ?
Предлагаю хотя бы дать название Title или что-то такое

2023-08-27 22:22 UTC, IvanPeleshok commented on packages/client/src/pages/GameToStart/index.tsx
> +        <div className={styles.loaderIcon}></div>
Отличная идея
Унификация - ключ к простоте и порядку

2023-08-27 22:23 UTC, IvanPeleshok requested changes
Проделана огромная работа!

Есть небольшие замечания у ваших коллег и у меня в частности
Просьба доработать :)

2023-08-29 17:13 UTC, IvanPeleshok approved these changes
Проделана огромная работа
Замечательная реализация
Апрув

2023-08-30 14:35 UTC, merged