Tsk 23 pass and avatar change
Ma1ve/BattleCity pull request #17
Opened 2023-08-26 08:10 UTC by stepanpr

### Добавление модальных окон смены пароля и смены аватара для страницы профиля.

![image](https://github.com/Ma1ve/BattleCity/assets/49967730/6630f6c4-6986-4ffa-b338-d29de4b8d2c0)

![image](https://github.com/Ma1ve/BattleCity/assets/49967730/003f1380-7c3d-4aa0-932f-938cb54a173e)

2023-08-26 09:41 UTC, IvanPeleshok requested changes
Необходим хотя бы один апрув  от члена команды перед тем, как отдавать работу на ревью в яндекс практикум

2023-08-27 09:52 UTC, Ma1ve approved these changes
Отличная работа!

2023-08-27 09:52 UTC, Ma1ve commented on packages/client/src/shared/api/UserActionsApi.ts
> +    return fetch(`${API_URL}/user/password`, {
Мы также можем использовать библиотеку axios для отправки запросов, думаю в дальнейшем это можно обсудить с командой, но лично я не возражаю использовать fetch . 

Думаю также при отправке запросов мы можем создать кастомный хук useAxios (или другой при отправке запросов на сервер )
Вот пример: https://dev.to/hey_yogini/useaxios-a-simple-custom-hook-for-calling-apis-using-axios-2dkj
Так мы не будем дублировать один и тот же код.

2023-08-27 09:52 UTC, Ma1ve commented on packages/client/src/shared/ui/ButtonProfile/buttonProfile.module.css
> +  color: var(--additional-text-color);
Хорошо, что выносишь все, что может повторятся в переменные

2023-08-27 09:52 UTC, Ma1ve commented on packages/client/src/shared/ui/Modal/index.tsx
> +    const bg = document.querySelector('#modal-bg')
Манипуляция напрямую с DOM в React может быть плохой практикой. возможны проблемы в будущем. 
Для достижения той же функциональности, можно создать хук
```
const [isModalOpen, setIsModalOpen] = useState(false);
```
И уже пробрасывать setIsModalOpen, вешать его на первый div на примере где находится  id="modal-bg"
```
 const handleBgClick = () => { setIsModalOpen(false) }
```
И уже на следующий div вешать onClick={ (e) => e.stopProppagation() }

Можно посмотреть пример, как это реализовать: 
https://www.youtube.com/watch?v=i2Yf7JZonB4&ab_channel=UlbiTV

2023-08-27 09:52 UTC, Ma1ve commented on packages/client/src/shared/ui/index.ts
> +export * from './Modal'
Хорошо, что вынес все в shared/ui, так мы сможем легче ориентироваться в проекте.

2023-08-27 18:56 UTC, stepanpr commented on packages/client/src/shared/ui/Modal/index.tsx
> +    const bg = document.querySelector('#modal-bg')
Да, спасибо, переделал на твой вариант

2023-08-27 22:25 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/ChangePasswordModal/index.tsx
> +export const validationSchema = Yup.object().shape({
Полагаю, что можно что-то похожее использовать при регистрации
Может быть вынесем схему валидации для унификации?

2023-08-27 22:26 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/index.tsx
> +  const [showChangeAvatarModal, setShowChangeAvatarModal] =
Рекомендация: конструкции следующего рода принято форматировать следующим образом:
```
const [
  va1, var2
] = var3
```

2023-08-27 22:27 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/index.tsx
> +        ).map((val, i) => {
Просьба не сокращать переменные, т.к код пишется для других членов команды и они должны с первого взгляда понимать контекст

2023-08-27 22:28 UTC, IvanPeleshok commented on packages/client/src/shared/api/UserActionsApi.ts
> +    return fetch(`${API_URL}/user/password`, {
Отличная идея
Просьба переписать на axios :)

Пример: https://stackoverflow.com/questions/63453491/how-to-export-axios-create-in-typescript#:~:text=I%20would%20suggest%20doing%20the%20following%3A

2023-08-27 22:29 UTC, IvanPeleshok commented on packages/client/src/shared/api/UserActionsApi.ts
> +      .then(result => result.json())
Не используем then / catch
Используем async / await + try / catch, чтобы код был плоским и писался в синхронной стилистике

2023-08-27 22:30 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Практически всё прекрасно, но есть небольшие замечания

2023-08-28 20:27 UTC, stepanpr commented on packages/client/src/pages/Profile/ChangePasswordModal/index.tsx
> +export const validationSchema = Yup.object().shape({
Да, при регистрации тоже уже используется схема валидации, возможно вынесем в отдельный файл в будущем

2023-08-30 05:05 UTC, IvanPeleshok approved these changes
Проделана огромная работа!
Вы молодец, хорошо потрудились)

Критических замечаний нет, работа принята!

2023-08-30 09:28 UTC, merged