Tsk 34/feature add fullscreen api
Ma1ve/BattleCity pull request #21
Opened 2023-09-05 21:14 UTC by vasilek-liza

Добавила описанное в уроках Web API  Fullscreen API

<img width="1433" alt="Снимок экрана 2023-09-06 в 00 13 27" src="https://github.com/Ma1ve/BattleCity/assets/72966820/5733fbfb-4705-4e99-bb71-f99d282ae83b">
 при наведении на кнопку появляется подсказка
 
 
<img width="1434" alt="Снимок экрана 2023-09-06 в 00 14 26" src="https://github.com/Ma1ve/BattleCity/assets/72966820/88893b9e-c380-4e1b-8531-fe72861f2d55">

2023-09-07 11:40 UTC, Ma1ve approved these changes
Отличная работа!

2023-09-07 11:40 UTC, Ma1ve commented on packages/client/src/shared/lib/toggleFullscreen.tsx
>      } else if (document.webkitExitFullscreen) {
Чтобы сделать код более надежным и учесть возможные различия в разных браузерах, нужно также добавить проверку ```!document.webkitFullscreenElement``` сверху, чтобы код выглядел так: 
```
if (
    !document.fullscreenElement &&
    !document.mozFullScreenElement &&
    !document.msFullscreenElement &&
    !document.webkitFullscreenElement
  )
```

2023-09-07 21:57 UTC, IvanPeleshok commented on packages/client/src/features/models/types.ts
> +export interface Document {
Разделяем пустой строкой блоки кода для читабельности

2023-09-07 21:59 UTC, IvanPeleshok commented on packages/client/src/shared/lib/toggleFullscreen.tsx
> +    !document.fullscreenElement &&
Обычно форматирование с && выглядит следующим образом:
```
if (
  var1
  && var2
  && var3
) {}
```

2023-09-07 22:01 UTC, IvanPeleshok commented on packages/client/src/shared/lib/toggleFullscreen.tsx
> +    if (setScreenSize) {
Предлагаю разделять логические блоки пустой строкой для лучшей читаемости

2023-09-07 22:02 UTC, IvanPeleshok commented on packages/client/src/shared/lib/toggleFullscreen.tsx
> +    if (setScreenSize) {
Аналогично

2023-09-07 22:04 UTC, IvanPeleshok commented on packages/client/src/shared/lib/toggleFullscreen.tsx
> +  } else {
Предлагаю не делать такую ветееватость с помощью else, если её можно избежать
```
if () {
  ..
  
  return
}

// else
```

2023-09-07 22:06 UTC, IvanPeleshok commented on packages/client/src/shared/ui/Button/index.tsx
>  export const Button: FC<IButton> = ({ children, type, ...rest }) => (
В данном случае, пропс className будет перезаписан, что может быть неочевидно
Может быть в рамках этой или другой задачки поправить и раширять классы, а не заменять?
Для этого можно воспользоваться либой classNames

2023-09-07 22:07 UTC, IvanPeleshok commented on packages/client/src/shared/lib/toggleFullscreen.tsx
> +  const elem = document.documentElement
Предлагаю не сокращать название переменных, сокомандники скажут спасибо
`element`

2023-09-07 22:09 UTC, IvanPeleshok commented on packages/client/src/shared/lib/toggleFullscreen.tsx
> +  const document = window.document as Document
В дальнейшем будет интеграция с Sever side rendering-ом, доступа к глобальному объекту docuemnt не будет
Есть возможность сейчас обыгать эту ситуацию

2023-09-07 22:10 UTC, IvanPeleshok commented on packages/client/src/shared/lib/toggleFullscreen.tsx
> +export const toggleFullscreen = (
Возможно более правильно в контексте реакта: написать кастомный хук, который будет возращать размер screenSize и метод модификации

2023-09-07 22:13 UTC, IvanPeleshok requested changes
Замечательная работа!
Видно, что в деталях изучили api fullscreen, потрясающе!

Предложил несколько вариантов доработок, которые не являются критическими (работу можно принять)

Запрошу изменения и что сочтете нужным - поправьте (можно и без правок получить апрув)

2023-09-09 08:54 UTC, IvanPeleshok requested changes
Поздравляю, работа принята!

Надеюсь, что запишите мои хотелки насчёт SSR и доработки пропсов для Button на будущее :)

Отлично постарались!
![image](https://github.com/Ma1ve/BattleCity/assets/70073003/323058da-5ac4-4184-a54e-5d63ecf65aeb)

2023-09-09 08:56 UTC, merged