[TKS-29] Add shots, block destructions
Ma1ve/BattleCity pull request #22
Opened 2023-09-08 18:50 UTC by theton1k

### Какую задачу решаем
Добавить выстрелы
Разрушения блоков при попадании снаряда
Исправить остановку танка (когда зажата клавиша движения и нажимается любая другая) 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-09-10 18:04 UTC, Ma1ve approved these changes
Отличная работа! В дальнейшем можно немного подправить спрайт танчика. Чтобы он не задевал другой спрайт (снизу) .

![213123](https://github.com/Ma1ve/BattleCity/assets/93385505/b42f72f8-71aa-410b-9672-14d98aa55603)

Также, но это уже попозже, можно подумать, как перемещать танчик при столкновении с блоком, когда допустим он упирается своим пикселем в край блока и едет на месте, как на скриншоте снизу. Можно попробовать, его перемещать на дорогу. Так играть будет значительно удобнее.

![123](https://github.com/Ma1ve/BattleCity/assets/93385505/c76ad183-bbe5-42ca-98c9-efc144405b4c)

2023-09-11 12:33 UTC, IvanPeleshok commented on packages/client/src/pages/Game/shared/utils/isCoordsArray.ts
> +): coords is Coords[] => {
Впервые такую запись вижу
Спасибо, что показал)

2023-09-11 12:34 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Bullet.ts
> +  public position
Предлагаю для всех сущностей задать тип

2023-09-11 12:35 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Bullet.ts
> +    let posX
Укажите явные типы при объявлении переменной

2023-09-11 12:36 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Bullet.ts
> +      case 'up':
MovementDirection не подойдёт, чтобы не использовать строковые?

2023-09-11 12:43 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Scene.ts
> +          ;(this.sceneBlocks[sceneBlockKey] as Coords[]) = searchedSceneBlock
полагаю ; лишняя

2023-09-11 12:43 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Scene.ts
> +    Object.values(this.tanks).forEach(tankArray => {
Сделано классно, нраица

2023-09-11 12:48 UTC, IvanPeleshok requested changes
Крутая работа, отлично потрудился!
Прикольно оптимизировал циклы, нраица)

Искренне хочется принять работу, но есть небольшие замечания

Достаточно будет добавить типы для сущностей класса и констурктора

2023-09-11 16:29 UTC, theton1k commented on packages/client/src/pages/Game/ui/Scene.ts
> +          ;(this.sceneBlocks[sceneBlockKey] as Coords[]) = searchedSceneBlock
это решение преттира)
при сохранении добавляет ;

2023-09-11 16:30 UTC, theton1k commented on packages/client/src/pages/Game/ui/Bullet.ts
> +  public position
а зачем?
тип данных берется из конструктора при присваивании
вроде как распространенная практика для того, чтобы не дублировать типизацию

2023-09-11 19:30 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Bullet.ts
> +  public position
@theton1k, написал небольшой пример: https://www.typescriptlang.org/play?#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNf0KArgEYgCWwhATgPYoCMOzB0wtAdhAC7VHDda1ABQo6KdNV4BPAFzQORJCUkBKbHlYFuAC3IQAdGPoNoAXhr1JMzVui79R8aYtYAvrege3QA

<img width="407" alt="Снимок экрана 2023-09-11 в 23 28 15" src="https://github.com/Ma1ve/BattleCity/assets/70073003/26d14d1a-19ff-402b-a7be-b4223bf377ae">

Как видно, ts не ругается

2023-09-11 19:33 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Bullet.ts
> +  public position
Если нет желания переписать и команда согласна, можете оставить)

2023-09-11 19:35 UTC, IvanPeleshok commented on packages/client/src/pages/Game/ui/Scene.ts
> +          ;(this.sceneBlocks[sceneBlockKey] as Coords[]) = searchedSceneBlock
Можно оставить так, согласен)

2023-09-11 20:07 UTC, theton1k commented on packages/client/src/pages/Game/ui/Bullet.ts
> +  public position
а, понял, спасибо!

2023-09-12 09:03 UTC, IvanPeleshok approved these changes
Отличная работа!
Апрув :)

2023-09-12 16:55 UTC, merged