add Start | GameOver | Level loading states
Ma1ve/BattleCity pull request #24
Opened 2023-09-08 19:51 UTC by Ma1ve

- Добавил начало и конец игры
- При нажатия на "Enter" пользователю показывается загрузка уроня
- После отображается GameOver, с дальнейшим отображением счёта

![йцуфыв](https://github.com/Ma1ve/BattleCity/assets/93385505/04917cf2-e6a7-44d7-91f6-7361f990bb40)
![stage](https://github.com/Ma1ve/BattleCity/assets/93385505/0550066c-54c7-449a-902d-e49bdf3b3674)
![gameover](https://github.com/Ma1ve/BattleCity/assets/93385505/8c62c7c8-24ab-49de-96f4-0de35633b553)
![SDFASDF](https://github.com/Ma1ve/BattleCity/assets/93385505/a8f1e270-8cc6-4a61-9318-f93e663e8f6e)

Также создал класс CanvasTextDrawer для более удобного взаимодействия с отображением текста на canvas

2023-09-08 21:18 UTC, theton1k requested changes
запустил прилагу - выглядит круто!

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/CanvasTextDrawer.ts
> +  spriteTank: any
есть тип CoordsWithSizeCoords

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/CanvasTextDrawer.ts
> +      spritePosition: { x: 17 * 32, y: 14.5 * 32, w: 16, h: 16 },
нужно спрайт вынести в GameUI

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/GameOverMenu.ts
> +        spriteTank: gameUI.images.tanks['silver']['armored']['up'][0],
через точку переход по ключам будет читабельнее

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/StartGameMenu.ts
> +    this.spriteImage = spriteImage
spriteImage в классе не используется
да и не должно
все спрайты используемые в игре по-хорошему должны находиться в GameUI, и оттуда уже тянуться в нужные места

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/CanvasTextDrawer.ts
> +    const yTankCanvasPosition = y - 37
по-хорошему вынести все такие числа в переменные, чтобы было понятие, что они такое

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/GameOverMenu.ts
> +      spritePosition: { x: 16 * 32, y: 5.2 * 32, w: 62, h: 62 },
нужно спрайт вынести в GameUI

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/StartGameMenu.ts
> +      spritePosition: { x: 8.5 * 32, y: 9.5 * 32, w: 420, h: 144 },
нужно спрайт вынести в GameUI

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/StartGameMenu.ts
> +      Sh: 144,
не соответствует остальному стилю кода camelCase

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/StartGameMenu.ts
> +      Sw: 32,
тоже camelCase

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/CanvasTextDrawer.ts
> +    y?: number | null
тут не замечание, а просто заметка
можно избежать типа `undefined | null | number`, если в функцию принимать объект
да, будет больше кода, но в принципе будет и читабельнее
большие дядьки мне советовали так делать)  
ну и ты где-то юзаешь объекты, а где-то передаешь через запятую
какой-то паттерн выбора варианта я не выявил, просто в глаза бросилось)

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/GameUI.ts
> +    Sh?: number
не совсем понял смысл этих параметров
у spritePosition уже есть sw и sh

размер блока 32
если твой спрайт занимает половину блока - sw и sh по 16 будут
если четверть - по 8

ну и новые параметры не в camelCase стиле

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/GameUI.ts
> +  }
найс штука!
если чуть переделать, то можно будет для всех анимаций юзать
некоторые спрайты имеют больше 2 отрисовок (мелкий взрыв - 3, возрождение - 4) 
переименуй мб на animateSprite или что-то подобное
чтобы было понятно, что функция анимирует спрайты

нужно будет передавать сюда и frameCount и весь массив спрайтов, чтобы плясать от длины массива

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/StartGameMenu.ts
> +        ],
лучше обращаться к ключам через точки

2023-09-08 21:18 UTC, theton1k commented on packages/client/src/pages/Game/ui/GameOverMenu.ts
> +    })
опять же, лучше вынести непонятные числа куда-нибудь в переменные
если я правильно понял, то завязка идет на размеры окна игры
так вот на случай, если мы решим сменить размер окна - тебе не придется переписывать везде по коду эти моменты

2023-09-11 12:02 UTC, theton1k approved these changes

2023-09-11 17:42 UTC, Ma1ve commented on packages/client/src/pages/Game/ui/GameUI.ts
> +    Sh?: number
Я это сделал, тк считаю, если я не буду передавать данные аргументы, у меня будет умножаться sw и sh на canvasItemScale, который равен 1.5. Из за того, что данные переменные также находятся выше в коде, я не смогу подстроить спрайт под нужный размер, на подобии надписи BattleCity, которая без переменных  sW и sH будет слишком большой или маленькой.
```
ctx.drawImage(
      this.spriteImage,
      sx,
      sy,
      sw,
      sh,
      cx,
      cy,
      sW ? sW : sw * canvasItemScale,
      sH ? sH : sh * canvasItemScale
    )
```

2023-09-12 17:11 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду.
В общем виде проблема - замешана логика и отображение. Классы, которые должны заниматься отрисовкой интерфейса занимаются переключением состояния, перезагрузкой страницы и т.д. и т.п.
Лучше реализовать контроллер, который хранит состояние и занимается переключением экранов и анимаций, а классы с методом draw() пусть только рисуют, и, возможно, сообщают о том что анимация завершена.

2023-09-12 17:11 UTC, Olegas commented on packages/client/src/pages/Game/ui/CanvasTextDrawer.ts
> +    const yC = y ? y : this.canvasHeight / 2 + fontSize / 2
А тут не должно быть так же как для x? (canvasHeight - fontSize) / 2?

2023-09-12 17:11 UTC, Olegas commented on packages/client/src/pages/Game/ui/GameOverMenu.ts
> +    this.totalNumberOfDestroyedTanks += this.tanksInfo.reduce(
На предыдущей строке присвоение 0 явно лишнее. Можно тут результат reduce просто присвоить.

2023-09-12 17:11 UTC, Olegas commented on packages/client/src/pages/Game/ui/GameOverMenu.ts
> +    }, 1000)
Вот такая штука достаточно странно выглядит с архитектурной точки зрения. Класс, занимающийся отрисовкой не должен принимать никаких решений о перезагрузке страницы. На мой взгляд этим должен заниматься какой-то другой класс, например тот же самый, что запускает метод draw тут

2023-09-12 17:11 UTC, Olegas commented on packages/client/src/pages/Game/ui/GameOverMenu.ts
> +    this.isGameOver = true // isGameOver проверяем завершена ли игра, будет true, когда флаг сломали
Кажется тут замешали отрисовку визуальной частик и часть состояния игры. Если в этом классе есть два экрана, которые надо переключать, в этом случае лучше сделать два класса и переключать их "снаружи", там где состояние игры "под рукой", а не тянуть состояние в представление.

2023-09-12 17:11 UTC, Olegas commented on packages/client/src/pages/Game/ui/LevelLoadingStage.ts
> +      }, 1000)
Тут тоже странный участок. Опять класс, занимающийся рисованием, выставляет какие-то флаги.
И вызов isGameLoaded странный. Он же просто булево значение возвращает, ничего не меняет.

2023-09-12 17:11 UTC, Olegas commented on packages/client/src/pages/Game/ui/StartGameMenu.ts
> +}
В этом классе та же история - замешано отображение и логика. А кроме этого еще и обработка событий. Совет: разделите состояние и отображение. И классы станут проще и код понятнее.

2023-09-12 20:45 UTC, theton1k commented on packages/client/src/pages/Game/ui/GameUI.ts
> +    Sh?: number
ну все правильно, оно умножится)
но ведь и весь канвас умножается на 1.5
соответственно и все элементы должны умножиться
это умножение на 1.5 чисто для того, чтобы спрайты не были мелкие
32 пикселя - это не играбельно

у тебя весь канвас размером 13x13
каждый полноценный блок это 32 пикселя
получаем размер 416x416
умножаем на itemScale (1.5)
получаем 624x624 - весь канвас

длина самого большого спрайта (battleCity) 12 блоков по 32 пикселя
после вывода на канвас получаем
12 * 32 * 1.5 = 575

```
battleCitySpriteWidth = 12 * spriteWidth // ширина на спрайте
battleCitySpriteHeight = 4.5 * spriteHeight // высота на спрайте
```

сам спрайт

```
      battleCity: getSpriteItemPosition({
        x: 8,
        y: 9.5,
        w: battleCitySpriteWidth,
        h: battleCitySpriteHeight,
      }),
```


 // canvasWidthWithoutScale - это columns * spriteWidth (13 * 32)


и в drawImage будет так
```
gameUI.drawImage({
      ctx: this.ctx,
      spritePosition: gameUI.images.stage.battleCity,
      canvasPosition: {
        x: (canvasWidthWithoutScale - battleCitySpriteWidth) / 2, // отцентровка (внутри само заскейлится на 1.5)
        y: this.positionY + this.battleCityTextIndentationByY, // так же заскейлится внутри
      },
    })

```

2023-09-14 12:35 UTC, Ma1ve commented on packages/client/src/pages/Game/ui/CanvasTextDrawer.ts
> +    const yC = y ? y : this.canvasHeight / 2 + fontSize / 2
Да, вы правы, только переменная yC будет по середине, когда будет сложение (canvasHeight + fontSize) / 2 

![уууу](https://github.com/Ma1ve/BattleCity/assets/93385505/faee8a42-5a7d-45e7-93e8-02415d567130)

2023-09-14 16:06 UTC, Olegas commented
@Ma1ve код переписан, но суть не поменялась. Вот смотри... У тебя есть классы, которые что-то рисуют (те, у которых есть метод draw). В этих классах не должно быть кода, который смотрит на контроллер игры, читает его свойства, зовет его методы. Все должно быть ровно наоборот.
Контроллер игры должен в зависимости от своего состояния создавать классы отрисовки и звать у них draw().
Тебе сейчас в коде нужно смотреть состояние, потому что у тебя в одном классе отрисовки смешаны две "картинки". И в методе draw тебе надо смотреть - рисовать это или то. Это тоже надо вытаскивать наружу. Сделай вместо одного класса два и пусть контроллер игры решает что именно нарисовать в какой момент.
Еще один очень странный момент - сеттеры, которые не сразу ставят переменную, а внутри таймаута. Такой код крайне сложно отлаживать, вообще странно что такая потребность есть - вызвать метод сейчас а поставить свойство потом.

2023-09-16 07:54 UTC, Olegas approved these changes
👍 Круто!
Работа принята, спасибо!

2023-09-25 20:57 UTC, merged