Tsk 32 service workers
Ma1ve/BattleCity pull request #26
Opened 2023-09-10 03:23 UTC by stepanpr

Добавление **ServiceWorker** в проект для кеширования статики.

2023-09-10 09:31 UTC, Ma1ve approved these changes
Отличная работа! Хорошая реализация SW

2023-09-11 18:17 UTC, Olegas requested changes
Добрый день.
Есть вопросы по коду + есть проблема - данное решение не будет работать в релизной сборке. Написал подробный комментарий и совет, как можно исправить.

2023-09-11 18:17 UTC, Olegas commented on packages/client/serviceWorker.js
> +]
Направление движения правильное. Но так не будет работать при релизной сборке приложения. Таких файлов в релизной сборке просто не будет. Если хочешь кэшировать статику и в релизе, почитай про файл-манифест, который можно сгенерировать при сборке и заинжектить его в код service worker
Например см. https://vite-pwa-org.netlify.app/workbox/inject-manifest.html

2023-09-11 18:17 UTC, Olegas commented on packages/client/serviceWorker.js
> +        cacheNames.filter(name => name).map(name => caches.delete(name))
Странная конструкция. Она отберет все кэши и удалит их. Думаю тут должно быть какое-то другое условие фильтрации списка кэшей

2023-09-15 14:37 UTC, stepanpr commented on packages/client/serviceWorker.js
> +]
service-worker теперь лежит в public, для локальной разработки и для прода работет.
По поводу injectManifest и workbox тоже разбирался, выглядит как удобное решение особенно вкупе с Vite, думаю добавим в будущем

2023-09-16 07:52 UTC, Olegas approved these changes

2023-09-18 13:38 UTC, merged