[TSK-39] Add leaderboard API
Ma1ve/BattleCity pull request #30
Opened 2023-10-02 17:19 UTC by theton1k

### Какую задачу решаем
Добавление LeaderboardAPI

### Скриншоты/видяшка (если есть)
<img width="698" alt="image" src="https://github.com/Ma1ve/BattleCity/assets/69811094/b1923163-b81a-4633-b4d3-3ce208e796c6">

### TBD (если есть)

2023-10-02 17:42 UTC, theton1k commented
Конфликты типов на девелопе
К задаче отношения не имеют

2023-10-02 20:44 UTC, Ma1ve approved these changes
Отличная работа

2023-10-03 10:15 UTC, Brarion requested changes
Хорошая работа, оставил 1 небольшое замечание

2023-10-03 10:15 UTC, Brarion commented on packages/client/src/shared/api/LeaderboardApi.ts
> +      store.getState().user.userInfo || {}
Лучше не использовать `store.getState()`
Для этого более верным решением будет передать `display_name`, `first_name` и `id` в метод `sendResult`, то есть в самом компоненте, где вызывается метод, нужно получить данные из стора, а после этого их передать в метод

2023-10-03 10:18 UTC, Brarion commented on packages/client/src/shared/api/LeaderboardApi.ts
> +      store.getState().user.userInfo || {}
Это также связано с тем, что стор будет "разбросан" по разным по смыслу кускам кода. То есть условно есть стор, есть UI, а если работа со стором будет ещё и в `API`, то будет уже сложнее намного, если проект вырастет в разы

2023-10-05 10:12 UTC, Brarion approved these changes
Так лучше, но ещё лучше будет вообще убрать стор из логики, стор работает по-хорошему либо сам с собой, либо с UI, а остальная логика выполняется посредством мидлваров или подобных инструментов, не стоит напрямую импортить стор в отдельную логику игры
В целом аппрув, но лучше дальше вынести ещё

2023-10-05 18:44 UTC, merged