TSK-36_add-bg-audio
Ma1ve/BattleCity pull request #33
Opened 2023-10-06 05:22 UTC by stepanpr

### Какую задачу решаем 
**Добавление фоновой музыки.**

![image](https://github.com/Ma1ve/BattleCity/assets/49967730/f53efb42-ab2e-4da6-966a-6231d2eac849)
![image](https://github.com/Ma1ve/BattleCity/assets/49967730/d059a42f-62a6-4c10-8a8c-521dafd01313)

2023-10-06 10:09 UTC, Ma1ve approved these changes
Отличная работа!

2023-10-06 10:09 UTC, Ma1ve commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +  const stop = () => {
Функции play() и pause() , имеют очень много общего, думаю лучше создать одну функцию, в которую будет передаваться определенный action и уже в зависимости от переданного значения будет выбор между: 

```audioRef.current.play()``` и ```audioRef.current.pause()```

Вот пример кода: 
```  
const toggleAudio = (action) => {
  if (audioRef.current) {
    if (action === 'play') {
      audioRef.current.play();
    } else if (action === 'pause') {
      audioRef.current.pause();
    }
  }
} 
```

2023-10-06 10:09 UTC, Ma1ve commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +      }
В handleAutoPlay, есть условие: 
```
if (audioRef.current) {
  audioRef.current.play()
}
```
Оно повторяет логику в функции play(), чтобы не писать лишний код, можно просто воспользоваться данной функцией.

2023-10-06 10:09 UTC, Ma1ve commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +        </div>
Можно потом при желании заменить Loading на какой то Spinner

2023-10-06 11:34 UTC, stepanpr commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +  const stop = () => {
Спасибо за проверку! Поправил!

2023-10-07 06:19 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +  const [volume, setVolume] = useState(0.2)
0.2 вынести в константу, не должно быть магических значений (DEFAULT_VOLUME)

2023-10-07 06:20 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +  const bgSoundsList: HTMLAudioElement[] = [
Полагаю, что можно вынести в константу вне компоненты

2023-10-07 06:21 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +export const BgAudioArea = () => {
Предлагаю не сокращать название компоненты (bg - what is it?)

2023-10-07 06:22 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +          handleAudioActionApply('play')
Предлагаю вынести в переменные / перечисление play / pause / stop и переиспользовать в дальнейшем

2023-10-07 06:23 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +  const handleAudioActionApply = (action: 'play' | 'pause' | 'stop') => {
Можно оптимизировать этот и ниже объявленные функции с помощью useCallback
https://reactdev.ru/reference/useCallback/#:~:text=useCallback%20%2D%20%D1%8D%D1%82%D0%BE%20%D1%85%D1%83%D0%BA%20React%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9,%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%BC%D0%B5%D0%B6%D0%B4%D1%83%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%BC%D0%B8%20%D1%80%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%B8%D0%BD%D0%B3%D0%B0%D0%BC%D0%B8.

2023-10-07 06:24 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +        onCanPlay={e => {
Предлагаю инлайн колбеки переписать на функции до return JSX, это сильно упрощает читаемость

2023-10-07 06:27 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +            onChange={e => {
Можно прокинуть в handleVolumeChange event от onChange, тогда запись станет немного читаемее
```
const handleVolumeChange = (event: HTMLInputElement<T>) => {...}

onChange={handleVolumeChange}
```

2023-10-07 06:28 UTC, IvanPeleshok commented on packages/client/src/features/ui/BgAudioArea/index.tsx
> +            onClick={() => isPlaying && changeTrack()}
Аналогично передавать ссылку на метод, а не колбек
isPlaying можно использовать внутри changeTrack

2023-10-07 06:29 UTC, IvanPeleshok requested changes
Проделана огромная работа!

Есть небольшие замечания, требуется доработка

Хорошего дня :)

2023-10-08 04:41 UTC, stepanpr commented
@IvanPeleshok 
Спасибо за проверку!! Внес правки по замечаниям. 
По поводу eslint - там падают тесты, коллега который их писал, сейчас в процессе исправления.
Спасибо!!!
Хорошего дня!

2023-10-08 12:21 UTC, IvanPeleshok approved these changes
Поздравляю, апрув 🚀 

Хорошего дня :)

2023-10-09 08:12 UTC, merged