[TSK-43] Forum API
Ma1ve/BattleCity pull request #34
Opened 2023-10-14 17:03 UTC by theton1k

### Какую задачу решаем
Forum API (topic, comment, reply)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-14 17:49 UTC, vasilek-liza approved these changes
Отличная работа!

2023-10-14 17:49 UTC, vasilek-liza commented on packages/server/db.ts
> +    await sequelize.sync() // Синхронизация базы данных
в теории был момент:  чтобы метод sync отслеживал изменения в моделях:  
await sequelize.sync({ force: true });

2023-10-15 13:43 UTC, IvanPeleshok requested changes
Проделана большая работа, отлично постарались!

Есть небольшие замечания, прошу доработать

Хорошего дня :)

2023-10-15 13:43 UTC, IvanPeleshok commented on packages/server/db.ts
> +// const { POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_PORT } =
Если не используется, предлагаю удалить ненужный функционал

2023-10-15 13:43 UTC, IvanPeleshok commented on packages/server/db.ts
> +  // try {
Аналогично
Если не используется -> удаляем

2023-10-15 13:43 UTC, IvanPeleshok commented on packages/server/db.ts
> +  user: 'antonastreiko',
Все поля необходимо вынести в переменные окружения

2023-10-15 13:43 UTC, IvanPeleshok commented on packages/server/docker-compose.yaml
> +      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/veisa
Предлагаю вынести в переменные окружения
https://docs.docker.com/compose/environment-variables/set-environment-variables/

Аналогично и другие значения для POSTGRES_PASSWORD, POSTGRES_USER и т.д

2023-10-15 13:43 UTC, IvanPeleshok commented on packages/server/src/routes/commentsRouter.ts
> +      console.log('newComment', newComment)
Не уверен, что отладочный код нужен в деве

2023-10-15 13:43 UTC, IvanPeleshok commented on packages/server/src/routes/topicsRouter.ts
> +    // @ts-ignore
По какой причине игнорим ts?

2023-10-15 13:43 UTC, IvanPeleshok commented on packages/server/src/routes/repliesRouter.ts
> +      res.status(200).json(newReply)
Когда создаётся новый ресурс, то статус ответа должен быть 201

https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP#:~:text=%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B4%D0%B0%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0%20%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%80%D1%83%D1%8E%D1%82%20%D0%BE%20%D1%81%D0%BB%D1%83%D1%87%D0%B0%D1%8F%D1%85%20%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BF%D1%80%D0%B8%D0%BD%D1%8F%D1%82%D0%B8%D1%8F%20%D0%B8%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8%20%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0%20%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0.%20%D0%92%20%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8%20%D0%BE%D1%82%20%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%B0%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D0%B5%D1%89%D1%91%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%82%D1%8C%20%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8%20%D0%B8%20%D1%82%D0%B5%D0%BB%D0%BE%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F.

2023-10-15 14:08 UTC, theton1k commented on packages/server/src/routes/topicsRouter.ts
> +    // @ts-ignore
потому что ts ругается на передаваемый объект
приходится объектам либо явно указывать тип как Optional<Reply, NullishPropertiesOf<Reply>>
либо игнорить

2023-10-15 19:21 UTC, IvanPeleshok commented on packages/server/src/routes/topicsRouter.ts
> +    // @ts-ignore
Предлагаю типизировать, а не обходить типизацию с помощью игноров

2023-10-15 19:23 UTC, IvanPeleshok approved these changes
Отлично потрудились
Поздравляю, работа принята!
Критических замечаний нет
Хорошего дня 🚀

2023-10-15 19:39 UTC, merged