Tsk 47/added theme change
Ma1ve/BattleCity pull request #35
Opened 2023-10-14 17:24 UTC by vasilek-liza

Реализовала клиентскую часть темизации.  
Тема по-умолчанию:  темная. Для неавторизованных пользователей, тема сохраняется в localStorage.
Серверная часть будет работоспособна после выполнения соответствующих спринтовых задач.

2023-10-14 18:17 UTC, theton1k approved these changes

2023-10-14 18:22 UTC, theton1k commented
🔥🔥🔥

2023-10-15 07:15 UTC, IvanPeleshok commented on packages/client/src/app/models/types.ts
> +export enum ETheme {
Название перечисление немного спорное, предлагаю убрать E

2023-10-15 07:18 UTC, IvanPeleshok commented on packages/client/src/app/router/RootLayout.tsx
> +    if (userInfo) {
Рекомендация: писать без else по возможности
```
if (var1) {
  ...
  
  return
}

// else
```

2023-10-15 07:20 UTC, IvanPeleshok commented on packages/client/src/entities/ui/Header/Header.tsx
> +  const changedTheme = () => {
changeTheme

2023-10-15 07:20 UTC, IvanPeleshok commented on packages/client/src/entities/ui/Header/Header.tsx
> +        onClick={() => changedTheme()}
Предлагаю передавать не колбек, а ссылку на метод
```
onClick{changeTheme}
```

2023-10-15 07:21 UTC, IvanPeleshok commented on packages/client/src/shared/api/AuthApi.ts
> +        `http://localhost:3001/theme?id=${id}`
Предлагаю вынести в переменную окружения http://localhost:3001

2023-10-15 07:22 UTC, IvanPeleshok commented on packages/client/src/shared/api/AuthApi.ts
> +      const response = await this.instance.post(`http://localhost:3001/theme`, {
Аналогично, http://localhost:3001 в енв

2023-10-15 07:25 UTC, IvanPeleshok commented on packages/server/controllers/controllerTheme.ts
> +            where: { userId: userId }
Можно было не дублировать название userId

2023-10-15 07:25 UTC, IvanPeleshok commented on packages/server/controllers/controllerTheme.ts
> +        response.status(201).json('ok');
Предлагаю возвращать объект созданной/изменённой темы в ответе вместо ok

2023-10-15 07:26 UTC, IvanPeleshok commented on packages/server/db.ts
> +    username: 'postgres',
По-хорошему, все поля необходимо вынести в переменные окружения

2023-10-15 07:28 UTC, IvanPeleshok commented on packages/client/src/app/router/RootLayout.tsx
> +      const currentTheme = await AuthAPI.getTheme(userInfo.id)
Разве у вас не используются санки?
Отличная возможность использовать функционал санки: обращаемся к апи сервера, устанавливаем состояние с хранилище

2023-10-15 07:29 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Отлично постарались!

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-10-15 09:39 UTC, vasilek-liza commented on packages/client/src/app/router/RootLayout.tsx
> +      const currentTheme = await AuthAPI.getTheme(userInfo.id)
Спасибо за совет, учтем в дальнейших доработках)

2023-10-15 12:54 UTC, IvanPeleshok commented on packages/client/src/shared/api/AuthApi.ts
> +      const response = await this.instance.post(`${LOCAL_HOST}/theme`, {
Предлагаю назвать переменную более подходящим образом
Тут идёт речь не о local host

2023-10-15 12:59 UTC, IvanPeleshok approved these changes
Критических замечаний не выявлено!

Поздравляю, апрув!

Хорошего дня 🚀 

Оставил маленький комменатрий

2023-10-15 13:15 UTC, merged