Added emojiAPI client
Ma1ve/BattleCity pull request #37
Opened 2023-10-15 12:17 UTC by archibald7812

### Какую задачу решаем
Добавление Emoji на клменте. Создание функций для получения эмодзи и отображения на клиенте

### Скриншоты/видяшка (если есть)
<img width="117" alt="Снимок экрана 2023-10-15 151633" src="https://github.com/Ma1ve/BattleCity/assets/96223816/9a6219fb-d6fc-4b3f-a16a-baa6b0a04c76">
### TBD (если есть)

2023-10-15 12:19 UTC, archibald7812 commented
Пока что добавил функционал для эмодзи на страницу EndGame, так как форум еще в работе. Также, это задача по клиентской части и серверная часть еще в разработке, соответственно для отображения эмодзи использовал .json файл с тем видом данных, которые будут приходить на запрос. Добавил обработку состояния загрузки и ошибки, использую RTQ.

2023-10-15 14:36 UTC, theton1k approved these changes

2023-10-15 19:25 UTC, IvanPeleshok commented on packages/client/src/app/store/api/emojiAPI.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'https://localhost:3001/emoji' }),
Использовать переменную окружения (https://localhost:3001)
Можно подсмотреть у сокомандников, их просил сделать аналогично

2023-10-15 19:26 UTC, IvanPeleshok commented on packages/client/src/components/EmojiWindow/EmojiWindow.tsx
> +    console.log(data)
Для какой цели отладочный код в деве?

2023-10-15 19:26 UTC, archibald7812 commented on packages/client/src/app/store/api/emojiAPI.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'https://localhost:3001/emoji' }),
Да, так будет лучше, спасибо

2023-10-15 19:27 UTC, archibald7812 commented on packages/client/src/components/EmojiWindow/EmojiWindow.tsx
> +    console.log(data)
Забыл убрать, он не нужен

2023-10-15 19:30 UTC, IvanPeleshok commented on packages/client/src/components/EmojiWindow/EmojiWindow.tsx
> +      {Object.values(data.emoji).map((emoji: string) => {
Предлагаю в преобразовать ответ в createApi с помощью `transformResponse`
https://medium.com/@lada496/rtk-query-how-to-modify-query-responses-with-transformresponse-18200f1f2484#:~:text=API%20slice,the%20API%20slice.
Пример:
```
export const starWarsApi = createApi({
  reducerPath: "starWarsApi",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://akabab.github.io/starwars-api/api/"
  }),
  endpoints: (builder) => ({
    getCharacters: builder.query<CategorizedCharacters, undefined>({
      query: () => "all.json",
      transformResponse: (response: RowCharacter[]): CategorizedCharacters => {
        if (response.length === 0) return {};
        const modifiedCharacters = modifyRowCharacters(response);
        const categorizedCharacters = categorizeCharacters(modifiedCharacters);
        return { all: modifiedCharacters, ...categorizedCharacters };
      }
    })
  })
});
```

2023-10-15 19:30 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Отлично постарались!

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-10-15 19:34 UTC, archibald7812 commented on packages/client/src/components/EmojiWindow/EmojiWindow.tsx
> +      {Object.values(data.emoji).map((emoji: string) => {
А какую цель мне преследовать при трансформации данных, если полученные данные вида 
{emoji: {1 : 'string', 2 : 'string'}}? Подскажите, как обычно преобразовывают данные в таком случае? Может преобразовать их как массив, чтобы не пришлось использовать Object.values()?

2023-10-15 19:55 UTC, IvanPeleshok commented on packages/client/src/components/EmojiWindow/EmojiWindow.tsx
> +      {Object.values(data.emoji).map((emoji: string) => {
Если не планируете использовать ключи объекта, то массив отлично бы подошёл

2023-10-15 20:50 UTC, archibald7812 commented on packages/client/src/components/EmojiWindow/EmojiWindow.tsx
> +      {Object.values(data.emoji).map((emoji: string) => {
Нет, все хорошо. Просто если посмотреть, то у меня в компоненте EmojiWindow идет отрисовка через Object.values():
`{Object.values(data.emoji).map((emoji: string) => {
        return (
          <span role="img" aria-label="Reaction">
            {emoji}
          </span>
        )
      })}`
      Соответственно, так у меня будет срабатывать Object.values() при каждом перерендере, а если сделать это в transformeResponse, то только один раз при получении данных, спасибо а реккомендацию!

2023-10-16 06:21 UTC, IvanPeleshok approved these changes
Замечательная работа!
Поздравляю, апрувчик

Хорошего дня :)

2023-10-16 15:12 UTC, merged