Tsk 48 forum
Ma1ve/BattleCity pull request #38
Opened 2023-10-18 08:04 UTC by stepanpr

### Добавление раздела форума

![image](https://github.com/Ma1ve/BattleCity/assets/49967730/67fad52d-0744-40e5-bb90-dc82570a670c)

![image](https://github.com/Ma1ve/BattleCity/assets/49967730/2ac1ba59-ccd8-4924-969c-161b27af8b6f)

![image](https://github.com/Ma1ve/BattleCity/assets/49967730/2a346a0c-fffa-455d-b7da-4a42461db5df)

2023-10-18 10:09 UTC, Ma1ve approved these changes
Отличная работа!

2023-10-18 18:48 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду, нужно доработать.
Написал комментарии по всем проблемным местам.

2023-10-18 18:48 UTC, Olegas commented on packages/client/src/shared/api/ForumApi.ts
> +}
Почему у этого типа все поля - опциональные? Разве может быть топик без идентификатора? Без автора? Без заголовка? Даже если в нем нет комментариев их просто 0 а не undefined.

2023-10-18 18:48 UTC, Olegas commented on packages/client/src/shared/api/ForumApi.ts
> +}
Аналогичны вопрос и тут - почему все поля опциональные?

2023-10-18 18:48 UTC, Olegas commented on packages/client/src/shared/api/ForumApi.ts
> +}
Аналогичны вопрос и тут - почему все поля опциональные?

2023-10-18 18:48 UTC, Olegas commented on packages/client/src/shared/api/ForumApi.ts
> +  getTopics = async (): Promise<{ data: ITopic[] } | undefined> => {
Кажется тут data в ответе - лишнее поле. Его можно достать внутри getTopics и вернуть сразу список. Так будет удобнее и понятнее для потребителя этого метода

2023-10-18 18:48 UTC, Olegas commented on packages/client/src/shared/api/ForumApi.ts
> +      console.error(error?.response?.data?.reason)
Если обработали ошибку, лучше уж тогда вернуть пустой массив вместо "ничего". Но правильнее не игнорировать ошибку а выкинуть ее дальше - пусть уже потребитель API разбирается как ее обработать - превратить в пустой список, показать окно пользователю или сделать что-то другое

2023-10-18 18:48 UTC, Olegas commented on packages/client/src/pages/Forum/ui/Forum.tsx
> +  }
Вот эти функции (выше, 3 штуки) имеет смысл обернуть в useMemo что бы не создавать их каждый раз новые на каждый рендер.

2023-10-19 00:59 UTC, stepanpr commented on packages/client/src/shared/api/ForumApi.ts
> +}
Согласен!

2023-10-19 17:20 UTC, Olegas requested changes
В текущем решении есть ошибка - использование return error вместо throw error. Написал подробный комментарий по месту.
+ один совет, тоже написал по месту

2023-10-19 17:20 UTC, Olegas commented on packages/client/src/shared/api/ForumApi.ts
> +      return error
Так не будет работать. Что бы в точке вызова сработал catch, ошибку нужно выбросить как исключение с помощью throw вместо return

2023-10-19 17:20 UTC, Olegas commented on packages/client/src/pages/Forum/ui/Forum.tsx
> +  const getTopics = useMemo(
Совет (не блокирует приемку работы): для мемоизации функций обычно используется useCallback. Текущее решение тоже работает, но выглядит не привычно. Там где предполагается функция ожидаешь увидеть useCallback а не useMemo

2023-10-20 11:23 UTC, Olegas approved these changes
Работа принята

2023-10-20 16:24 UTC, merged